name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build common library
      run: npx nx build common
    
    - name: Build auth service
      run: npx nx build auth-service
    
    - name: Build gateway service
      run: npx nx build gateway
    
    - name: Run tests
      run: npx nx run-many --target=test --all

  deploy-auth:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy Auth Service to Render
      uses: johnbeynon/render-deploy-action@v1.0.0
      with:
        service-id: ${{ secrets.RENDER_AUTH_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-gateway:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy Gateway Service to Render
      uses: johnbeynon/render-deploy-action@v1.0.0
      with:
        service-id: ${{ secrets.RENDER_GATEWAY_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
